### PR TITLE
Defined end-to-end test for metadata bundle update

### PR DESCRIPTION
**Pull request by rdgoite**
This PR is to address the issue with the original PR(#454) branch being branched off of `integration` instead of `master`. Please check the link to the original for some additional context.

### CODE REVIEW

**Comment by parthshahva** [comment]
@rdgoite did you confirm that test_smartseq2_run and test_optimus also work with these code changes?

**Comment by maniarathi** [comment]
Hey Rodrey, could you please run a linter on this to make sure the nits are taken care of before submission? Thanks!

**Comment by rdgoite** [comment]
> @rdgoite did you confirm that test_smartseq2_run and test_optimus also work with these code changes?

I haven't run either with these changes, but the metadata update test effectively extends the ss2 test, with some of the assertions taken out, so I'm quite positive it should work. I was able to run the ss2 test before after my refactoring. There are no direct changes to optimus test, and I think the changes I made to runner are minimal.

**Comment by rdgoite** [comment]
@maniarathi you mean in the context of my changes or the codebase in general? I've seen quite a bit of linting issues all over the codebase, and I don't think I can address all of them. It also doesn't look like we've set up a whitelist on this repo so I'm overwhelmed with the results.

**Comment by maniarathi** [comment]
For posterity, Rodrey and I discussed linting offline.

**Comment by rdgoite** [comment]
As communicated on Slack, we have merged the changes to `master`.

**Pull request merged**
